_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 32
criterion:
    value: mse
hidden_layers:
    value:
        - 8
lr:
    value: 0.001
model_type:
    value: MLP_Classifier
num_epochs:
    value: 10000
optimizer:
    value: bgd
wandb_run_name:
    value: shaunak1
